# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 451a16965c100e8384ff7bd9064c7a69c46b6b96980e9231be28889b04928c86a4e14ce25d06d0b0f221112489945bf2f7f191be53a1ea57bd457de28437c237

test:
  secret_key_base: 03f284c8da26c564e065814df5ec0a27792ac8f411003786807e2a4a5f8e305c0fa13fd1d52fe2260920016dc81c824b5b88bbd39c2a820d8005a91d4ea0a600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
